# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 459a8a072c8c96a629865eb71da5eb24d879dd6919a78b2cd18da8b833e5d64971addbb09bb74527e99fd883b75bc4e2e46850b4f4e5544dd28cbe2f3e4bc857

test:
  secret_key_base: 4ce8680e3974ef12f26c63f1c95250b69437417a445242d45ed73b4a9bb753f9ecf93183be52d9b95e08e430de4a680e0df2be1c1725dd23056565e7619b5060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
